#!/bin/bash

# update the computer
apt update
apt -y full-upgrade

# install fusuma (touchpad gestures)
# add user to input group
gpasswd -a $USER input
apt-get install libinput-tools
apt-get install libevdev-dev
apt install ruby-dev
gem install fusuma
apt-get install xdotool
gem update fusuma

# install fusuma plugins
gem install fusuma-plugin-sendkey
gem install fusuma-plugin-wmctrl
gem install fusuma-plugin-keypress
gem install fusuma-plugin-tap

# install python3.8
apt install python3.8

# intall pip3
apt install python3-pip

# install python3-venv
apt-get install python3-venv

# install node and npm
apt install nodejs
apt install npm

# install sqlite3
apt install sqlite3

# install chromium
apt install chromium-browser

# install vscode
snap install --classic code

# install spotify
snap install spotify

# install git
apt install git

# set user.email and user.name
git config --global user.email "maxiecody@gmail.com"
git config --global user.name "codythegreat"

# install docker
apt install docker.io

# install jdk-14
apt install openjdk-14-jdk

# install go
apt install golang

# install curl
apt install curl

# install ranger
apt install ranger

# install tmux
apt install tmux

# install vim
apt install vim

# get dotfiles
./dotfiles
